### ISSUE TITLE
How is the Tempo Interval Managed?

### ISSUE THREAD

**Issue by loganknecht** [deemaagog/piano-blues-maker#2]
Hello there,

Apologies for the double issue creation (see #1). I was a bit embarrassed linking to the original VexFlow thread.

I've been reading through your code in this repo, and it is absolutely fantastic. You've done an absolutely wonderful job of separating concerns.

I had a question regarding how the tempo is managed correctly in your Player.

When I look through `src/service/Player.js` I can see that the `setTimeout` function is used to perform the looped callbacks, but I'm confused at how `curEvent.duration * 1000` is configured. More so I'm also confused as to how it's managed through out the lifecycle of the song.

If you could provide any guidance on understanding how the tempo is kept in order to highlight the notes I would love to know more. Particularly, as my goal is to use Vex Flow so that I can draw an overlay bar that keeps pace with the tempo over the song, and then do additional functionality like you've achieved.

**Comment by deemaagog** [comment]
thank you 
Basic durations (in seconds) are stored in constants.js. Actual durations are calculated by a simple formula  dur * 60 / tempo .  "curEvent.duration * 1000" is just conversion seconds to milliseconds
Each iteration of playback process consists of steps: 
a) play one note accordingly to its duration.  Highlight note and turn off  highlight using setTimeout
b) schedule "step a"  accordingly to the time  until next note (0 if a chord)
 Hope I helped you
